### ISSUE TITLE
Can avatar2 not only emulate firmware but also debug firmware? Thank you !

### ISSUE THREAD

**Issue by sssyyynnngithub** [avatartwo/avatar2#41]

**Comment by mariusmue** [comment]
Hi @sssyyynnngithub.
Enabling firmware emulation is the main entry point for all sorts of dynamic analysis, including debugging. If you are able to run your firmware for instance in the GDB/QEMU target, you can make use of the provided gdb stubs, and control execution and memory via the provided avatar2-apis.

If  you have any specific questions, please let us know, otherwise I'll close this issue in a couple of days.

Cheers!
